name: Build and Release ClipPocket

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: macos-13  # Specify a more recent macOS runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.0'  # Specify the latest Xcode version

      - name: List Xcode versions
        run: ls -l /Applications/ | grep Xcode

      - name: Show Xcode version
        run: xcodebuild -version

      - name: List project contents
        run: ls -R

      - name: Build ClipPocket
        run: |
          xcodebuild clean build -project ClipPocket.xcodeproj -scheme ClipPocket -configuration Release -derivedDataPath build

      - name: Create DMG
        run: |
          brew install create-dmg
          create-dmg \
            --volname "ClipPocket" \
            --window-pos 200 120 \
            --window-size 800 400 \
            --icon-size 100 \
            --icon "ClipPocket.app" 200 190 \
            --hide-extension "ClipPocket.app" \
            --app-drop-link 600 185 \
            "ClipPocket.dmg" \
            "./build/Release/ClipPocket.app"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ClipPocket ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload DMG to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./ClipPocket.dmg
          asset_name: ClipPocket.dmg
          asset_content_type: application/x-apple-diskimage
